github_monitor_config:
  token:
  monitoring_scheme: 5
  update_key:
    - cve-{year}
    - cve-{year_1}
    - cve-{year_2}
    - cve-{year_3}
    - cve-{year_4}
    - cve-{year_5}
    - cve-{year_6}
  enable_exact_match: true
  push_config:
    lowest_star: 2
    growth_warning_star:
      - 5
      - 20
      - 50
    name_warning_count:
      - 3
      - 6

mysql_config:
  host: 'localhost'
  port: 3306
  user: 'root'
  password: '@123456z'

push_config:
  server_chan:
    send_key:

schedule:
  github_run:
    # trigger 参数可以是: interval 或 cron
    trigger: cron
    hour: 5,11,17,20
    minute: 0
  push:
    trigger: cron
    hour: 5,11,17,20
    minute: 30