github_monitor_config:
  # 配置 github token （在 https://github.com/settings/tokens/new 生成）。
  token: ghp_15phroQOJtruJIaNPqa2614xxxxxxxxxxxxxx
  # 配置监控的关键词，{year}会替换为最新的年份
  # 如果 {year} 为 2022 年，那么 {year-1} 为 2021 年，依此类推最大为 {year-10}。
  # 也可以使用其它关键词，如：RCE 等。
  update_key:
    - cve-{year}
    - cve-{year_1}
    - cve-{year_2}
    - cve-{year_3}
    - cve-{year_4}
    - cve-{year_5}
    - cve-{year_6}
    - rce
    - Remote Command Execution
  # 是否启用精确匹配，启用后将只匹配仓库名，关闭将匹配配仓库名和描述。
  enable_exact_match: false
  monitoring:
    # 设置标星和仓库数量的监控时长。
    duration: 20
    # 同时监控项目的最大数量。
    max_number: 300
  # Github 推送过滤配置。
  push_config:
    # Github 更新推送的最低标星。
    lowest_star: 2
    # Github 标星监控，标星增长推送的最低标星。
    # 5，15，50 表示分别在仓库增长超过 5、15、50 星时推送，一个仓库有可能会推送三次。
    growth_warning_star:
      - 5
      - 15
      - 50
    # Github 仓库数量监控，仓库数量增长推送的最低数量。
    name_warning_count:
      - 3
      - 6

# mysql 数据库配置
# 需要 mysql 5.6 或以上的版本
mysql_config:
  db: 'exp-monitoring'
  host: 'localhost'
  port: 3306
  user: 'root'
  password: 'root'

# 推送配置
push_config:
  # Server酱推送配置
  server_chan:
    # 是否启用该方式推送
    enable: false
    send_key: SCT63558ToWsvMZ0vUbcxxxxxxxxxxxxxx
  email:
    enable: false
    # 邮箱服务器
    smtp_server: 'smtp.qq.com'
    smtp_port: 465
    # 发信方邮箱
    from_addr: 'xxxxxxxxxx@qq.com'
    # 邮箱授权码
    # qq 邮箱在【设置】->【账户】中开启 POP3/SMTP 服务后获得授权码
    password: altaqwgwuxxxxxxxx
    # 收信方邮箱
    to_addr: 'xxxxxxxxx@qq.com'
  dingding:
    enable: false
    # 钉钉“加签”时需获得的密钥
    secret: SEC17dd116b6ec43d22559908f98f80f59c1ff6axxxxxxxxxxxxxxxxxx
    # 钉钉群自定义机器人 webhook 地址中的 access_token 字段
    access_token: 64303b06af10d356f758b41935e08adfe571f35xxxxxxxxxxxxxxxxxxx


# 计划任务配置
schedule:
  # github 运行计划任务配置
  github_run:
    # trigger 参数可以是: interval 或 cron
    # trigger: interval
    # hour: 1
    # 表示每 1 小时运行一次
    # trigger: cron
    # hour: 5,7,9,11-13
    # minute: 0
    # 表示在每天的 5、7、9点整和 11、12、13 点整运行
    trigger: cron
    hour: 5,11,17,20,23
    minute: 0
  # 推送计划任务配置
  # 配置推送的时间，默认在 github 监控运行半小时后推送
  push:
    trigger: cron
    hour: 5,11,17,20,23
    minute: 30